/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.com.getsoftware.davicalcados.gui.cadastro;

import br.com.getsoftware.davicalcados.bo.ProdutoBO;
import br.com.getsoftware.davicalcados.entity.Cliente;
import br.com.getsoftware.davicalcados.entity.Produto;
import static br.com.getsoftware.davicalcados.entity.UsuarioLogado.usuarioLogado;
import br.com.getsoftware.davicalcados.entity.Venda;
import br.com.getsoftware.davicalcados.gui.lista.ListClientesGUI;
import br.com.getsoftware.davicalcados.gui.lista.ListProdutosGUI;
import br.com.getsoftware.davicalcados.util.DataAtual;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Junior Oliveira
 */
public class CadVendaGUI extends javax.swing.JFrame {

    /**
     * Creates new form CadVendaGUI1
     */
    private final ArrayList<ItensCarrinho> itensCarrinho = new ArrayList<>();
    
    public CadVendaGUI() {
        initComponents();
        atualizaLinhaSelecionada();
        jFid.requestFocus();
        jLdata.setText(DataAtual.dataAtual());
        jLuser.setText(usuarioLogado.getUserName());
    }
    
    private Produto produto;
    public Produto getProduto() {
        return produto;
        
    }

    public void setProduto(Produto produto) {
        this.produto = produto;
    }
    
    public CadVendaGUI(Produto produto) {
        this();
        initComponents();
        this.produto = produto;
         setarValoresProduto();
         atualizaLinhaSelecionada();
         jFid.requestFocus();
         
    }

    public Cliente getCliente() {
        return cliente;
    }

    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }

    public CaixaGUI getCaixa() {
        return caixa;
    }

    public void setCaixa(CaixaGUI caixa) {
        this.caixa = caixa;
    }
    public void setarValoresProduto(){
        jFproduto.setText(produto.getNome());
        jFid.setText(""+produto.getIdProduto());
        jFvalor.setText("" + produto.getValorVenda());
        
          ItensCarrinho itens = new ItensCarrinho();
          itens.setIdProduto(produto.getIdProduto());
          itens.setNome(produto.getNome());
          itens.setQuantidadeRealDoEstoque(produto.getQuantidade());
            boolean encontreiOItem = false;
            for (int i = 0; i < itensCarrinho.size(); i++) {
                if (itensCarrinho.get(i).equals(itens)) {
                    jFestoque.setText("" + (produto.getQuantidade() - itensCarrinho.get(i).getQuantidade()));
                    encontreiOItem = true;
                    break;
                }
            }
            if(!encontreiOItem){
               jFestoque.setText("" + (produto.getQuantidade())); 
            }
        jFquantidade.requestFocus();

    }
     
    private Cliente cliente;
    public CadVendaGUI(Cliente cliente) {
        this();
        initComponents();
        this.cliente = cliente;
        jFcliente.setText(cliente.getNome());
        atualizaLinhaSelecionada();
//        jFid.requestFocus();

    }
    public void setarValoresClient(){
         jFcliente.setText(cliente.getNome());
    }
    private CaixaGUI caixa;
    public CadVendaGUI(CaixaGUI caixa) {
        this();
        this.caixa = caixa;
//        jFid.requestFocus();
    }

    private int linhaSelecionada;
    public void atualizaLinhaSelecionada() {
        linhaSelecionada = -1;
        jTable1.getSelectionModel().setSelectionInterval(linhaSelecionada, linhaSelecionada);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jFcliente = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        jBremover = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jBinserir = new javax.swing.JButton();
        jBaddProduto = new javax.swing.JButton();
        jFvalor = new javax.swing.JFormattedTextField();
        jFid = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jFproduto = new javax.swing.JFormattedTextField();
        jFestoque = new javax.swing.JFormattedTextField();
        jFquantidade = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jBaddProduto1 = new javax.swing.JButton();
        jBcancelar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLdata = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLuser = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jBfinalizar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLtotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 0, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cadastro de venda");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(356, 356, 356)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Cliente");

        jFcliente.setEditable(false);
        jFcliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        jFcliente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Quantidade disponível");

        jBremover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/getsoftware/davicalcados/icons/shop-cart-exclude-icon.png"))); // NOI18N
        jBremover.setText("ajustar");
        jBremover.setToolTipText("Ajustar quantidade de itens do produto selecionado");
        jBremover.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBremover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBremoverActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("ID do Produto");

        jBinserir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/getsoftware/davicalcados/icons/shop-cart-add-icon.png"))); // NOI18N
        jBinserir.setText("inserir");
        jBinserir.setToolTipText("Inserir produto na lista de compras");
        jBinserir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBinserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBinserirActionPerformed(evt);
            }
        });

        jBaddProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/getsoftware/davicalcados/icons/Start-Menu-Search-icon.png"))); // NOI18N
        jBaddProduto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBaddProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBaddProdutoActionPerformed(evt);
            }
        });

        jFvalor.setEditable(false);
        jFvalor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.MEDIUM))));
        jFvalor.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jFvalor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFvalorActionPerformed(evt);
            }
        });

        jFid.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jFid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jFidFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFidFocusLost(evt);
            }
        });
        jFid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFidActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Valor");

        jFproduto.setEditable(false);
        jFproduto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        jFproduto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jFestoque.setEditable(false);
        jFestoque.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.MEDIUM))));
        jFestoque.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jFestoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFestoqueActionPerformed(evt);
            }
        });

        jFquantidade.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jFquantidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jFquantidadeKeyReleased(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Quantidade no carrinho");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Produto");

        jBaddProduto1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/getsoftware/davicalcados/icons/Start-Menu-Search-icon.png"))); // NOI18N
        jBaddProduto1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBaddProduto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBaddProduto1ActionPerformed(evt);
            }
        });

        jBcancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/getsoftware/davicalcados/icons/cancelar-32.png"))); // NOI18N
        jBcancelar.setText("Cancelar");
        jBcancelar.setToolTipText("Cancelar venda");
        jBcancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcancelarActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Funcionário");

        jLdata.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLdata.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLdata.setText("xx/xx/xxxx");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Data da venda");

        jLuser.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLuser.setForeground(new java.awt.Color(51, 51, 255));
        jLuser.setText("jLabel12");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jBinserir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBremover)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBcancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jFestoque, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel9)
                                    .addComponent(jFquantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jFid, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jFvalor, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(292, 292, 292))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jFcliente)
                                        .addComponent(jFproduto))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jBaddProduto)
                                        .addComponent(jBaddProduto1))))
                            .addComponent(jLabel6))
                        .addGap(9, 9, 9))
                    .addComponent(jLdata, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLuser, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLdata, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLuser, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jFcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBaddProduto1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jFproduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBaddProduto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFvalor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFestoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFquantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBinserir, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(jBremover, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBcancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jBcancelar, jBinserir, jBremover});

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CÓDIGO", "PRODUTO", "QTD. ESTOQUE", "QUANTIDADE", "PREÇO", "TOTAL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
        }

        jBfinalizar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBfinalizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/getsoftware/davicalcados/icons/App-Catalog-icon.png"))); // NOI18N
        jBfinalizar.setText("FINALIZAR VENDA");
        jBfinalizar.setToolTipText("Definir a forma de pagamento");
        jBfinalizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBfinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBfinalizarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Total Geral");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("R$");

        jLtotal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLtotal.setText("00,00");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBfinalizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jLtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBfinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLtotal)))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1021, 519));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBremoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBremoverActionPerformed
       if (Integer.valueOf(jFestoque.getText()) < Integer.valueOf(jFquantidade.getText())) {
            JOptionPane.showMessageDialog(null, "Quantidade inválida!\nA quantidade no carrinho é superior a quantidade disponível.", "Atenção!", 2);
            jFquantidade.setText(null);
            jFquantidade.requestFocus();
        }else{
        removerCarrinho();
        mostraItensCarrinho();
        atualizaLinhaSelecionada();
        limparCapos();
           calcularTotalGeral();
       }
    }//GEN-LAST:event_jBremoverActionPerformed

    private void jBinserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBinserirActionPerformed

        if (jFid.getText() == null || jFid.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Campo 'ID do Produto' está vazio!", "Atenção!", 2);
            jFid.requestFocus();
        } else if (jFquantidade.getText() == null || jFquantidade.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Campo 'Quantidade no carrinho' está vazio!", "Atenção!", 2);
            jFquantidade.requestFocus();
        } else if (Integer.valueOf(jFestoque.getText()) < Integer.valueOf(jFquantidade.getText())) {
            JOptionPane.showMessageDialog(null, "Quantidade inválida!\nA quantidade no carrinho é superior a quantidade disponível.", "Atenção!", 2);
            jFquantidade.setText(null);
            jFquantidade.requestFocus();
        } else {
            inserirCarrinho();
            mostraItensCarrinho();
            atualizaLinhaSelecionada();
            limparCapos();
        }
        calcularTotalGeral();
    }//GEN-LAST:event_jBinserirActionPerformed

    private void jBaddProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBaddProdutoActionPerformed
        try {
            this.setEnabled(false);
            new ListProdutosGUI(this).setVisible(true);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Não foi possível listar os produtos", "Erro", 0);
            this.dispose();
        }
    }//GEN-LAST:event_jBaddProdutoActionPerformed

    private void jFvalorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFvalorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFvalorActionPerformed

    private void jFestoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFestoqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFestoqueActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        linhaSelecionada = jTable1.getSelectedRow();
        
        if(linhaSelecionada != -1){
        jFid.setText(jTable1.getValueAt(linhaSelecionada, 0).toString());
        jFproduto.setText(jTable1.getValueAt(linhaSelecionada, 1).toString());
        jFestoque.setText(jTable1.getValueAt(linhaSelecionada, 2).toString());
        jFquantidade.setText(jTable1.getValueAt(linhaSelecionada, 3).toString());
        jFvalor.setText(jTable1.getValueAt(linhaSelecionada, 4).toString());
        
        }
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jBfinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBfinalizarActionPerformed
         if(jFcliente.getText() == null || jFcliente.getText().isEmpty()){
           JOptionPane.showMessageDialog(null, "Campo 'Cliente' é obrigatório!", "Atenção", 2);
           jFcliente.requestFocus();
       }
       else if(itensCarrinho.isEmpty()){
           JOptionPane.showMessageDialog(null, "A lista de compra está vazia!!", "Atenção", 2);
           jBaddProduto.requestFocus();
       }
        else{
        Venda venda = new Venda();
        
        venda.setIdCliente(cliente.getIdCiente());
        venda.setIdFuncionario(Integer.valueOf(usuarioLogado.getIdUsuario()+""));
        venda.setData(DataAtual.dataAtual());
        ArrayList<String> listIdProdutos = new ArrayList();
        for (int i = 0; i < itensCarrinho.size(); i++) {
            listIdProdutos.add(itensCarrinho.get(i).getIdProduto());
        }
        venda.setListaIdProduto(listIdProdutos);
        venda.setValorTotal(Double.valueOf(jLtotal.getText()));
        this.setEnabled(false);
//        this.dispose();
        new FormaDePagamento(venda, this).setVisible(true);
       }
    }//GEN-LAST:event_jBfinalizarActionPerformed

    private void jFquantidadeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFquantidadeKeyReleased
         
    }//GEN-LAST:event_jFquantidadeKeyReleased

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        caixa.setEnabled(true);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void jBaddProduto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBaddProduto1ActionPerformed
        try {
            this.setEnabled(false);
            new ListClientesGUI(this).setVisible(true);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Não foi possível listar os clientes", "Erro", 0);
            this.dispose();
        }
    }//GEN-LAST:event_jBaddProduto1ActionPerformed

    private void jBcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcancelarActionPerformed
        caixa.setEnabled(true);
         this.dispose();
    }//GEN-LAST:event_jBcancelarActionPerformed

    public void jFidActionPerformed(){
        jFidActionPerformed(null);
    }
    
    private void jFidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFidActionPerformed
        String cod = (jFid.getText());
        try {
            produto = ProdutoBO.getById(cod);
            if(produto == null){
                 int opc = JOptionPane.showConfirmDialog(null, "Produto não encontrado!\n\nDeseja cadastrá-lo gora ?","Atenção",JOptionPane.YES_NO_OPTION);
                 if(opc == JOptionPane.YES_OPTION){
                     this.setEnabled(false);
                     new CadProdutoGUI(this).setVisible(true);
                 }else{
                     limparCapos();
                 }
            }else{
                setarValoresProduto();
//                jFquantidade.requestFocus();
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Não foi possível encontrar o produto","Erro",0);
            this.dispose();
        }
    }//GEN-LAST:event_jFidActionPerformed

    private void jFidFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFidFocusGained
        if(jFid.getText() == null || jFid.getText().isEmpty()){
            limparCapos();
        }
    }//GEN-LAST:event_jFidFocusGained

    private void jFidFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFidFocusLost
        if(jFid.getText() == null || jFid.getText().isEmpty()){
            limparCapos();
        }
    }//GEN-LAST:event_jFidFocusLost

    public void limparCapos(){
        jFquantidade.setText(null);
        jFproduto.setText(null);
        jFid.setText(null);
        jFvalor.setText(null);
        jFestoque.setText(null);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadVendaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadVendaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadVendaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadVendaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new CadVendaGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBaddProduto;
    private javax.swing.JButton jBaddProduto1;
    private javax.swing.JButton jBcancelar;
    private javax.swing.JButton jBfinalizar;
    private javax.swing.JButton jBinserir;
    private javax.swing.JButton jBremover;
    private javax.swing.JFormattedTextField jFcliente;
    private javax.swing.JFormattedTextField jFestoque;
    private javax.swing.JTextField jFid;
    private javax.swing.JFormattedTextField jFproduto;
    private javax.swing.JTextField jFquantidade;
    private javax.swing.JFormattedTextField jFvalor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLdata;
    private javax.swing.JLabel jLtotal;
    private javax.swing.JLabel jLuser;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    public void inserirCarrinho() {
        ItensCarrinho itens = new ItensCarrinho();
        itens.setIdProduto(produto.getIdProduto());
        itens.setNome(produto.getNome());
        itens.setQuantidade(Integer.valueOf(jFquantidade.getText()));
        itens.setValorVenda(produto.getValorVenda());
        itens.setQuantidadeRealDoEstoque(produto.getQuantidade());
        for (int i = 0; i < itensCarrinho.size(); i++) {
            if (itensCarrinho.get(i).equals(itens)) {
                itensCarrinho.get(i).setQuantidade(itensCarrinho.get(i).getQuantidade() + itens.getQuantidade());
                break;
            }
        }

        if (!itensCarrinho.contains(itens)) {
            itensCarrinho.add(itens);
        }

    }

      public void removerCarrinho() {
        ItensCarrinho itens = new ItensCarrinho();
        itens.setIdProduto((jTable1.getValueAt(linhaSelecionada, 0).toString()));
        itens.setNome(jTable1.getValueAt(linhaSelecionada, 1).toString());
        itens.setQuantidade(Integer.valueOf(jFquantidade.getText()));
        itens.setValorVenda(Double.valueOf(jTable1.getValueAt(linhaSelecionada, 3).toString()));

        for (int i = 0; i < itensCarrinho.size(); i++) {
             if (itensCarrinho.get(i).equals(itens)) {
                itensCarrinho.get(i).setQuantidade(Integer.valueOf(jFquantidade.getText()));
                break;
            }
        }

    }

      
    public void mostraItensCarrinho(){
        
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        modelo.setNumRows(0);

        for (int i = 0; i < itensCarrinho.size(); i++) {
            modelo.addRow(new Object[]{
                itensCarrinho.get(i).getIdProduto(),
                itensCarrinho.get(i).getNome(),
                itensCarrinho.get(i).getQuantidadeRealDoEstoque(),
                itensCarrinho.get(i).getQuantidade(),
                itensCarrinho.get(i).getValorVenda(),
                itensCarrinho.get(i).getTotal()
            });
        }
    }
    public void calcularTotalGeral(){
        Double total = 0.00;
        for (int i = 0; i < itensCarrinho.size(); i++) {
             total = total + itensCarrinho.get(i).getTotal();
        }
        jLtotal.setText(""+total);
    }
}
