/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.com.getsoftware.davicalcados.gui.cadastro;

import br.com.getsoftware.davicalcados.bo.ProdutoVendidoBO;
import br.com.getsoftware.davicalcados.bo.VendaBO;
import br.com.getsoftware.davicalcados.entity.ProdutoVendido;
import br.com.getsoftware.davicalcados.entity.Venda;
import br.com.getsoftware.davicalcados.util.TransformMoeda;
import javax.swing.JOptionPane;

/**
 *
 * @author Junior Oliveira
 */
public class FormaDePagamento extends javax.swing.JFrame {

    /**
     * Creates new form FormaDePagamento
     */
    public FormaDePagamento() {
        initComponents();
        bloqueaCampos();
        campoNaoAlterados();
         jTvalor.setText(""+500);
        jTvalorVenda.setText(""+500);
    }
    private CadVendaGUI cadVenda;
    private Venda venda;
    public FormaDePagamento(Venda venda, CadVendaGUI cadVenda) {
        this();
        this.venda = venda;
        
        this.cadVenda = cadVenda;
//        jTdesconto
//        jTecebido
//                jTentrada
//        jTtroco
        jTvalor.setText(""+venda.getValorTotal());
        jTvalorVenda.setText(""+venda.getValorTotal());
//        jTvalorVenda
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jCpagamento = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTvalor = new javax.swing.JTextField();
        jTdesconto = new javax.swing.JTextField();
        jTentrada = new javax.swing.JTextField();
        jTecebido = new javax.swing.JTextField();
        jTtroco = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTvalorVenda = new javax.swing.JTextField();
        jCparcela = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jBcancelar = new javax.swing.JButton();
        jBfinalizar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Forma de pagamento");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Forma de pagamento");

        jCpagamento.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCpagamento.setForeground(new java.awt.Color(204, 0, 0));
        jCpagamento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--FORMA DE PAGAMENTO--", "1 - Dinheiro", "2 - Cartão", "3 - Boleto", "4 - Carné" }));
        jCpagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCpagamentoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Total");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Desconto");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Entrada");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Valor Recebido");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Troco");

        jTvalor.setEditable(false);
        jTvalor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTvalor.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTvalor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTvalorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTvalorFocusLost(evt);
            }
        });
        jTvalor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTvalorKeyReleased(evt);
            }
        });

        jTdesconto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTdesconto.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTdesconto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTdescontoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTdescontoFocusLost(evt);
            }
        });
        jTdesconto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTdescontoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTdescontoKeyTyped(evt);
            }
        });

        jTentrada.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTentrada.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTentrada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTentradaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTentradaKeyTyped(evt);
            }
        });

        jTecebido.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTecebido.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTecebido.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTecebidoFocusLost(evt);
            }
        });
        jTecebido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTecebidoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTecebidoKeyTyped(evt);
            }
        });

        jTtroco.setEditable(false);
        jTtroco.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTtroco.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel9.setText("VALOR TOTAL DA VENDA");

        jTvalorVenda.setEditable(false);
        jTvalorVenda.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTvalorVenda.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jCparcela.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCparcela.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Parcelas--", "1x", "2x", "3x", "4x", "5x", "6x", "7x", "8x", "9x", "10x", "11x", "12x" }));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Nº de parcelas");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("R$");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("R$");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("R$");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("R$");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("R$");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("R$");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jTdesconto, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jCparcela, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(jCpagamento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTvalor))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTvalorVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel9)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jTentrada, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTtroco, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTecebido, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCpagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTvalor, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTdesconto, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                        .addComponent(jCparcela))
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTentrada, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTecebido, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTtroco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTvalorVenda)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jTdesconto, jTecebido, jTentrada, jTtroco, jTvalor, jTvalorVenda});

        jBcancelar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBcancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/getsoftware/davicalcados/icons/Apps-preferences-web-browser-adblock-icon.png"))); // NOI18N
        jBcancelar.setText("Cancelar");
        jBcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcancelarActionPerformed(evt);
            }
        });

        jBfinalizar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBfinalizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/getsoftware/davicalcados/icons/App-Catalog-icon.png"))); // NOI18N
        jBfinalizar.setText("Finalizar venda");
        jBfinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBfinalizarActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(204, 0, 0));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Finalizar venda");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBfinalizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBcancelar)))
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jBcancelar, jBfinalizar});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBcancelar)
                    .addComponent(jBfinalizar))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jBcancelar, jBfinalizar});

        setSize(new java.awt.Dimension(364, 629));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTvalorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTvalorKeyReleased
        jTvalor.setText(jTvalor.getText().replaceAll("[^0-9 | ^. | ^,]", ""));
    }//GEN-LAST:event_jTvalorKeyReleased

    private void jTvalorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTvalorFocusGained
//        jTvalor.setText(TransformMoeda.trasnformMoeda(jTvalor.getText()));
    }//GEN-LAST:event_jTvalorFocusGained

    private void jTvalorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTvalorFocusLost
//        jTvalor.setText(TransformMoeda.trasnformMoeda(jTvalor.getText()));
    }//GEN-LAST:event_jTvalorFocusLost

    private void jCpagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCpagamentoActionPerformed
        if (jCpagamento.getSelectedIndex() == 0) {
           bloqueaCampos();
        }
        if (jCpagamento.getSelectedIndex() == 1) {
            vendaDinheiro();
        }
        if (jCpagamento.getSelectedIndex() == 2) {
            vendaCartao();
        }
        if (jCpagamento.getSelectedIndex() == 3) {
            vendaBoleto();
        }
        if (jCpagamento.getSelectedIndex() == 4) {
            vendaCarne();
        }
    }//GEN-LAST:event_jCpagamentoActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
           this.dispose();
           cadVenda.setEnabled(true);
    }//GEN-LAST:event_formWindowClosing

    private void jBcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcancelarActionPerformed
        this.formWindowClosing(null);
    }//GEN-LAST:event_jBcancelarActionPerformed

    private void jBfinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBfinalizarActionPerformed
       
        
         if (jCpagamento.getSelectedIndex() == 0) {
             JOptionPane.showMessageDialog(null, "Deve-se selecioar uma forma de pagamento.", "Atenção!", 2);
             jCpagamento.requestFocus();
         }
         else if (jCpagamento.getSelectedIndex() == 1) {
              
          }
         else if (jCpagamento.getSelectedIndex() == 2) {
              
          }
         else if (jCpagamento.getSelectedIndex() == 3) {
              
          }
         else if (jCpagamento.getSelectedIndex() == 4) {
              
          }
         
        else{
             try {
                 VendaBO.save(venda);
                 for (int i = 0; i < venda.getListaIdProduto().size(); i++) {
                     ProdutoVendido prod = new ProdutoVendido();
                     prod.setId_produto(Long.parseLong(""+venda.getListaIdProduto().get(i)));
                     prod.setId_venda(Long.parseLong(""+venda.getIdVenda()));
                     ProdutoVendidoBO.save(prod);
                 }
                 JOptionPane.showMessageDialog(rootPane, "Venda realizada com sucesso!.", "Sucesso!!", 1);
                 this.dispose();
             } catch (Exception ex) {
                 JOptionPane.showMessageDialog(rootPane, "Não foi possível salvar a venda.", "Erro!", 0);
             }
        }

    }//GEN-LAST:event_jBfinalizarActionPerformed

    private void jTentradaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTentradaKeyReleased
         if(jTentrada.getText() != null || !jTentrada.getText().isEmpty() ){
            if(Float.valueOf(jTvalor.getText()) > Float.valueOf(jTentrada.getText())){
               jTvalorVenda.setText(""+(Float.valueOf(jTvalor.getText()) - Float.valueOf(jTentrada.getText())));
            }else{
                jTentrada.setText("0");
              JOptionPane.showMessageDialog(rootPane, "O valor do entrada é maior que o valor da venda, mude !", "Atenção!", 2);
               
            }
       }
        
    }//GEN-LAST:event_jTentradaKeyReleased

    private void jTdescontoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTdescontoKeyTyped
       String caracteres="0987654321.";
       if(!caracteres.contains(evt.getKeyChar()+"")){
       evt.consume();
       }if(jTdesconto.getText() == null || jTdesconto.getText().isEmpty() ){
           jTdesconto.setText("0");
       }
    }//GEN-LAST:event_jTdescontoKeyTyped

    private void jTdescontoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTdescontoKeyReleased
       if(jTdesconto.getText() != null || !jTdesconto.getText().isEmpty() ){
            if(Float.valueOf(jTvalor.getText()) > Float.valueOf(jTdesconto.getText())){
               jTvalorVenda.setText(""+(Float.valueOf(jTvalor.getText()) - Float.valueOf(jTdesconto.getText())));
            }else{
                jTdesconto.setText("0");
              JOptionPane.showMessageDialog(rootPane, "O valor do desconto não pode ser maior que o valor da venda!", "Atenção!", 2);
               
            }
       }
        
    }//GEN-LAST:event_jTdescontoKeyReleased

    private void jTdescontoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTdescontoFocusGained
        jTdesconto.setText("");
    }//GEN-LAST:event_jTdescontoFocusGained

    private void jTdescontoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTdescontoFocusLost
        if(jTdesconto.getText() == null || jTdesconto.getText().isEmpty() ){
           
       }
    }//GEN-LAST:event_jTdescontoFocusLost

    private void jTentradaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTentradaKeyTyped
        String caracteres="0987654321.";
       if(!caracteres.contains(evt.getKeyChar()+"")){
       evt.consume();
       }if(jTentrada.getText() == null || jTentrada.getText().isEmpty() ){
           jTentrada.setText("0");
       }
    }//GEN-LAST:event_jTentradaKeyTyped

    private void jTecebidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTecebidoKeyTyped
         String caracteres="0987654321.";
       if(!caracteres.contains(evt.getKeyChar()+"")){
       evt.consume();
       }if(jTecebido.getText() == null || jTecebido.getText().isEmpty() ){
           jTecebido.setText("0");
       }
    }//GEN-LAST:event_jTecebidoKeyTyped

    private void jTecebidoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTecebidoKeyReleased
         
        
    }//GEN-LAST:event_jTecebidoKeyReleased

    private void jTecebidoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTecebidoFocusLost
        if(jTecebido.getText() != null || !jTecebido.getText().isEmpty() ){
            if(Float.valueOf(jTecebido.getText()) >= Float.valueOf(jTvalorVenda.getText())){
                 
               jTtroco.setText(""+(Float.valueOf(jTecebido.getText()) - Float.valueOf(jTvalorVenda.getText())));
            }else{
                jTdesconto.setText("0");
              JOptionPane.showMessageDialog(rootPane, "O valor recebido é menor que o valor total da compra", "Atenção!", 2);
               
            }
       }
        
    }//GEN-LAST:event_jTecebidoFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormaDePagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormaDePagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormaDePagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormaDePagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormaDePagamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBcancelar;
    private javax.swing.JButton jBfinalizar;
    private javax.swing.JComboBox jCpagamento;
    private javax.swing.JComboBox jCparcela;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTdesconto;
    private javax.swing.JTextField jTecebido;
    private javax.swing.JTextField jTentrada;
    private javax.swing.JTextField jTtroco;
    private javax.swing.JTextField jTvalor;
    private javax.swing.JTextField jTvalorVenda;
    // End of variables declaration//GEN-END:variables

    private void campoNaoAlterados(){
         jTvalor.setEditable(false);
         jTtroco.setEditable(false);
         jTvalorVenda.setEditable(false);
    }
    
    private void bloqueaCampos() {
        jTdesconto.setEnabled(false);
        jTecebido.setEnabled(false);
        jTentrada.setEnabled(false);
        jCparcela.setEnabled(false);
        limpaCampos();
    }
    
    private void vendaDinheiro() {
        jTdesconto.setEnabled(true);
        jTecebido.setEnabled(true);
        jTentrada.setEnabled(false);
        jCparcela.setEnabled(false);
        limpaCampos();
    }
    private void vendaCartao() {
        jTdesconto.setEnabled(false);
        jTecebido.setEnabled(true);
        jTentrada.setEnabled(true);
        jCparcela.setEnabled(true);
        limpaCampos();
    }
    private void vendaBoleto() {
        jTdesconto.setEnabled(false);
        jTecebido.setEnabled(true);
        jTentrada.setEnabled(true);
        jCparcela.setEnabled(true);
        limpaCampos();
    }
    private void vendaCarne() {
        jTdesconto.setEnabled(false);
        jTecebido.setEnabled(true);
        jTentrada.setEnabled(true);
        jCparcela.setEnabled(true);
        limpaCampos();
    }
    private void limpaCampos(){
        jTdesconto.setText(null);
        jTecebido.setText(null);
        jTentrada.setText(null);
        jTtroco.setText(null);
        jTvalorVenda.setText(jTvalor.getText());
        jCparcela.setSelectedIndex(0);
    }
}
